services:
  uniqa:
    image: rodkin/uniqa_env
    environment:
        - "TG_BOT_TOKEN=${TG_BOT_TOKEN}"
    command: "bash run.sh"
    ports:
      - "8200:8200"
    depends_on:
      - graph
      - odqa
  graph:
    image: kirill456z/graph-model:v4
    ports:
      - "8001:5000"
    command: flask run
  odqa:
    image: rodkin/odqa_env
    command: "bash run.sh"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - 8141:8141
  response_refinement:
    image: natriistorm/response_refiner
    ports:
          - "8030:8030"